### ISSUE TITLE
master uses lionengine 8.4.0-snapshot, which is not available

### ISSUE THREAD

**Issue by wodencafe** [b3dgs/warcraft-remake#3]
I cannot get this sample to work, because it is using lionengine 8.4.0-snapshot, which I can't find anywhere and can't get to build from the lionengine branch.

Should this sample, at least in master, be using a version of lionengine that can't be resolved as a dependency without manually building that version of lionengine?

**Comment by DjThunder** [comment]
This is because i'm currently working on both (8.4.0 should be ready soon), and I did not created a branch for this project, as it is currently too little for that. Anyway, next time i will keep commit locally only, in order to avoid such a problem for people who are using it.
Sorry for troubles.

**Comment by wodencafe** [comment]
No problem, can you give me some info on how to build lionengine 8.4.0 snapshot? 
Are there instructions for building the jars?

**Comment by DjThunder** [comment]
Just clone the branch of 8.4.0 : https://github.com/b3dgs/lionengine/tree/lionengine-8.4.0
Run mvn clean install and it should be ok for using the core part.

**Comment by DjThunder** [comment]
But it will be better to use an older version of warcraft (checkout a previous commit, before January), as you may have errors (i'm currently fixing them). In this case it will use lionengine 8.3.6, which is available online.

**Comment by wodencafe** [comment]
Thanks for the info @DjThunder :+1: :)

**Comment by wodencafe** [comment]
It looks like the previous commits also rely on a version of lionengine that does not exist, **8.3.0-SNAPSHOT**.

When I switch the version to regular 8.3.0, I get compilation failures:

`[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project warcraft-game: Compilation failure: Compilation failure:
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[22,27] error: cannot find symbol
[ERROR] symbol:   class Graphic
[ERROR] location: package com.b3dgs.lionengine
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[25,32] error: cannot find symbol
[ERROR] symbol:   class Camera
[ERROR] location: package com.b3dgs.lionengine.game
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[26,32] error: cannot find symbol
[ERROR] symbol:   class WorldGame
[ERROR] location: package com.b3dgs.lionengine.game
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[30,39] error: package com.b3dgs.lionengine.game.object does not exist
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[31,39] error: package com.b3dgs.lionengine.game.object does not exist
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[32,39] error: package com.b3dgs.lionengine.game.object does not exist
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[33,39] error: package com.b3dgs.lionengine.game.object does not exist
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[34,39] error: package com.b3dgs.lionengine.game.object does not exist
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[41,27] error: cannot find symbol
[ERROR] symbol: class WorldGame
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[44,18] error: cannot find symbol
[ERROR] symbol:   class Services
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[46,18] error: cannot find symbol
[ERROR] symbol:   class Camera
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[48,18] error: cannot find symbol
[ERROR] symbol:   class Factory
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[50,18] error: cannot find symbol
[ERROR] symbol:   class Handler
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[78,23] error: cannot find symbol
[ERROR] symbol:   class Graphic
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/Scene.java:[22,27] error: cannot find symbol
[ERROR] symbol:   class Graphic
[ERROR] location: package com.b3dgs.lionengine
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/Scene.java:[94,23] error: cannot find symbol
[ERROR] symbol:   class Graphic
[ERROR] location: class Scene
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[44,42] error: cannot find symbol
[ERROR] symbol:   class Services
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[46,50] error: cannot find symbol
[ERROR] symbol:   class Camera
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[48,52] error: cannot find symbol
[ERROR] symbol:   class Factory
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[50,52] error: cannot find symbol
[ERROR] symbol:   class Handler
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[64,33] error: cannot find symbol
[ERROR] symbol:   class ComponentUpdater
[ERROR] location: class World
[ERROR] /home/cboyd/workspaces/wc3/warcraft-remake/warcraft-game/src/main/java/com/b3dgs/warcraft/World.java:[66,34] error: cannot find symbol
[ERROR] symbol:   class ComponentRenderer
[ERROR] location: class World
`

**Comment by DjThunder** [comment]
I can't make it work now, also there is nothing really interesting for the moment on this prototype, as I restarted it from scratch. If you want to read something more interesting, try with tyrian-remake.
I will publish 8.4.0 in June, with updated games (I hope).

**Comment by DjThunder** [comment]
I'm also updating it to make it run on android.

**Comment by DjThunder** [comment]
Project updated with LionEngine 8.4.0 and running on Android.

**Comment by wodencafe** [comment]
Good work @DjThunder, I will check it out later.
