### ISSUE TITLE
Make master branch working

### ISSUE THREAD

**Issue by SomeFire** [b3dgs/warcraft-remake#37]
## Expected Behavior
Working master branch.

## Actual Behavior
Compilation error [Orientable isn't Feature](https://github.com/b3dgs/warcraft-remake/commit/7aa82e417438c5943bbe1cca9b68a8f9d73aa707#diff-8bb792008b25c619691d41af23c30a36R80).

Also, some attributes are missed in Archer.xml.

## Steps to Reproduce the Problem

Launch AppWarcraftPc on master branches.

## Specifications

  - Warcraft Remake Version: [0.0.4](https://github.com/b3dgs/warcraft-remake/commit/ed95fe222a5238b04e8903b791fbc4ab0b4413d6)
  - Lionengine Version: [9.0.2-SNAPSHOT](https://github.com/b3dgs/lionengine/commit/cd9c7038697c093162fa802bcbccfb714e2902b4)

**Comment by DjThunder** [comment]
Yes sorry, still some work not committed yet on LionEngine-9.0.2-SNAPSHOT.

**Comment by DjThunder** [comment]
Should be fine after https://github.com/b3dgs/lionengine/commit/da9d847d21bd4c0121f8e77bb40c33a06efdb25f and https://github.com/b3dgs/lionengine/commit/679e7ab56c36bf898083b60608c4c1d7f77c935e
