### ISSUE TITLE
Fix cut forest tiles

### ISSUE THREAD

**Issue by SomeFire** [b3dgs/warcraft-remake#39]
## Expected Behavior
Extract wood by a single tile.

## Actual Behavior

Extracting wood replaces several tiles instead of 1. Replaced tile can be any tile. See [screenshot](https://pp.userapi.com/c853520/v853520990/a783f/8peW-bgAzG0.jpg).

## Steps to Reproduce the Problem

Order peon to extract trees.

## Specifications

  - Warcraft Remake Version: 0.0.4

**Comment by DjThunder** [comment]
Yes, as see here (https://github.com/b3dgs/warcraft-remake/commit/6504a2ca8467fb4ff90a0f19386a8d13a2c8022e), it simply need a generated transition file with all transitions on the same level. The current one is not correct enough.

**Comment by DjThunder** [comment]
To generate again the transition file, use the following code (same will have to be done for water and grass light and dark in order to use a level editor with automatic tile resolution on mouse edition)

```
TransitionsConfig.exports(Medias.create("map/forest/transitions.xml"),
                                  Arrays.asList(Medias.create("map/forest/transitions.png")),
                                  Medias.create("map/forest/sheets.xml"),
                                  Medias.create("map/forest/groups.xml"));
```
transitions.xml will be saved in your systemp temp folder under AppWarcraft/map/forest.
