### ISSUE TITLE
Stop woodcut animation when another order received

### ISSUE THREAD

**Issue by SomeFire** [b3dgs/warcraft-remake#41]
## Expected Behavior
Moving animation.

## Actual Behavior
Woodcut animation.

## Steps to Reproduce the Problem

  1. Order to extract wood.
  2. While extracting order to move.

## Specifications

  - Warcraft Remake Version: 0.0.4

**Comment by DjThunder** [comment]
May also be the same for Attack and Construction. There is currently no link between current order and other one.
