### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by adriancoloma** [b3dgs/warcraft-remake#53]
I can't build the project with maven.

**Comment by DjThunder** [comment]
Can you send me the build error trace ?

**Comment by cadri2001** [comment]
I ran "mvn build " in warcraft-pc folder and I got this:

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.b3dgs.warcraft:warcraft-parent:0.0.7-SNAPSHOT: Could not find artifact com.b3dgs:b3dgs-parent:pom:1.1.7-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.b3dgs.warcraft:warcraft-parent:0.0.7-SNAPSHOT, /home/cadri/Programas/Github/warcraft-remake/warcraft-parent/pom.xml, line 4, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.b3dgs.warcraft:warcraft-pc:0.0.7-SNAPSHOT (/home/cadri/Programas/Github/warcraft-remake/warcraft-pc/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.b3dgs.warcraft:warcraft-parent:0.0.7-SNAPSHOT: Could not find artifact com.b3dgs:b3dgs-parent:pom:1.1.7-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ com.b3dgs.warcraft:warcraft-parent:0.0.7-SNAPSHOT, /home/cadri/Programas/Github/warcraft-remake/warcraft-parent/pom.xml, line 4, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException


Am I executing the wrong command?

**Comment by DjThunder** [comment]
I updated the project with the latest engine snapshot. Build is working.
